//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlak.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vlak.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlak (Train) for WP7, v{0}, Author: Martin Suchan, martin.suchan@outlook.com.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sure :).
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string BuyLater {
            get {
                return ResourceManager.GetString("BuyLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By purchasing this game you will encourage the author for creating more great games. Buy now?.
        /// </summary>
        public static string BuyThisGame {
            get {
                return ResourceManager.GetString("BuyThisGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon!.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picked cargo or closed gate..
        /// </summary>
        public static string DoNotHitCargo {
            get {
                return ResourceManager.GetString("DoNotHitCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not hit the wall,.
        /// </summary>
        public static string DoNotHitWall {
            get {
                return ResourceManager.GetString("DoNotHitWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just finished the game Vlak, you must be really good.
        /// </summary>
        public static string FinishedGame {
            get {
                return ResourceManager.GetString("FinishedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck :).
        /// </summary>
        public static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and then reach the open gate:.
        /// </summary>
        public static string GoToGate {
            get {
                return ResourceManager.GetString("GoToGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulation!.
        /// </summary>
        public static string Gratulation {
            get {
                return ResourceManager.GetString("Gratulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no, you have just crashed! Tap anywhere to restart current level..
        /// </summary>
        public static string HowToPlayCrashed {
            get {
                return ResourceManager.GetString("HowToPlayCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have just finished the first level. Tap anywhere to enter next level..
        /// </summary>
        public static string HowToPlayFinished {
            get {
                return ResourceManager.GetString("HowToPlayFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial in the first level will also teach you gestures for steering the train..
        /// </summary>
        public static string HowToPlayHint {
            get {
                return ResourceManager.GetString("HowToPlayHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play - tap around the train or use flick gesture to start the game..
        /// </summary>
        public static string HowToPlayReady {
            get {
                return ResourceManager.GetString("HowToPlayReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap in the highlighted areas or use flick gestures to change the direction..
        /// </summary>
        public static string HowToPlayStarted {
            get {
                return ResourceManager.GetString("HowToPlayStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original author: Miroslav Němeček, GEMAsoft Rožnov pod Radhoštěm.
        /// </summary>
        public static string OriginalAuthor {
            get {
                return ResourceManager.GetString("OriginalAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-line score.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is You:.
        /// </summary>
        public static string ThisIsYou {
            get {
                return ResourceManager.GetString("ThisIsYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version.
        /// </summary>
        public static string TrialNotice {
            get {
                return ResourceManager.GetString("TrialNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sure I am :).
        /// </summary>
        public static string YesIAm {
            get {
                return ResourceManager.GetString("YesIAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your goal is in each level to pick up all the cargo ....
        /// </summary>
        public static string YourGoalIs {
            get {
                return ResourceManager.GetString("YourGoalIs", resourceCulture);
            }
        }
    }
}
